### ISSUE TITLE
Add `io.Writer` method

### ISSUE THREAD

**Issue by chewxy** [chewxy/skiprope#4]

**Comment by codegoalie** [comment]
@chewxy Just to be clear is this issue to implement the `io.Writer` interface on `Rope`? I.e. `func (r *Rope)  Write(p []byte) (n int, err error)`. Should this append or overwrite the current Rope contents? If so, I can take this, I think.

**Comment by chewxy** [comment]
Yes. Correct on all points. Please do take this. Thanks

On 22 Oct. 2017 5:02 am, "Chris Marshall" <notifications@github.com> wrote:

@chewxy <https://github.com/chewxy> Just to be clear is this issue to
implement the io.Writer interface on Rope? I.e. func (r *Rope) Write(p
[]byte) (n int, err error). Should this append or overwrite the current
Rope contents? If so, I can take this, I think.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chewxy/skiprope/issues/4#issuecomment-338421062>, or mute
the thread
